
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 6;
  public static final int MULTIPLICACION = 19;
  public static final int ANIMAR_TIPO_CURVA = 14;
  public static final int DECIMAL = 26;
  public static final int DIVISION = 20;
  public static final int SUMA = 17;
  public static final int CURVA = 16;
  public static final int ANIMAR = 8;
  public static final int COLOR = 12;
  public static final int CUADRADO = 4;
  public static final int OBJETO = 9;
  public static final int ID = 24;
  public static final int GRAFICAR = 2;
  public static final int LINEAL = 15;
  public static final int COMA = 23;
  public static final int EOF = 0;
  public static final int ANIMAR_TIPO_LINEAL = 13;
  public static final int OBJETO_ANTERIOR = 11;
  public static final int PAR2 = 22;
  public static final int error = 1;
  public static final int POLIGONO = 7;
  public static final int PAR1 = 21;
  public static final int CIRCULO = 3;
  public static final int ENTERO = 25;
  public static final int ANTERIOR = 10;
  public static final int RECTANGULO = 5;
  public static final int RESTA = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GRAFICAR",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "LINEA",
  "POLIGONO",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "OBJETO_ANTERIOR",
  "COLOR",
  "ANIMAR_TIPO_LINEAL",
  "ANIMAR_TIPO_CURVA",
  "LINEAL",
  "CURVA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PAR1",
  "PAR2",
  "COMA",
  "ID",
  "ENTERO",
  "DECIMAL"
  };
}

